import { VerticalBox, HorizontalBox, LineEdit, CheckBox, Button } from "std-widgets.slint";
import { StateLayer } from "state_layer.slint";

export component Background inherits Rectangle {
    width: 360px;
    height: 240px;
    background: rgb(255,228,181);
    border-radius: 20px;
    drop-shadow-blur: 16px;
    drop-shadow-color: rgba(0, 0, 0, 0.4);
    drop-shadow-offset-x: 0;
    drop-shadow-offset-y: 4px;
}

export component CountdownText inherits Text {
    text: "距离截止日期还有 100 天";
    font-size: 32px;
    font-family: "Microsoft Yahei UI";
    font-weight: 600;
    color: red;
    horizontal-alignment: left;
    vertical-alignment: top;
    wrap: word-wrap;
}

export component FloatButton {
    in property <image> icon <=> i-icon.source;
    in property <bool> enabled <=> i-state-layer.enabled;

    callback clicked <=> i-state-layer.clicked;

    width: 30px;
    height: 30px;

    i-container := Rectangle {
        background: #fff;
        border-radius: max(self.width, self.height) / 2;

        i-icon := Image {
            width: 20px;
            height: 20px;
            colorize: #000;
        }
    }

    i-state-layer := StateLayer {
        border-radius: i-container.border-radius;
    }
}

export component DragArea inherits TouchArea {
    width: 100%;
    height: 100%;
    mouse-cursor: pointer;

    property <bool> drag-pressed: false;
    property <length> drag-start-x: 0;
    property <length> drag-start-y: 0;

    callback on-move-window(length, length);

    moved => {
        if (drag-pressed) {
            on-move-window(self.mouse-x - drag-start-x, self.mouse-y - drag-start-y);
        }
    }

    pointer-event(ev) => {
        if (ev.button == PointerEventButton.left) {
            if (ev.kind == PointerEventKind.down) {
                drag-pressed = true;
                drag-start-x = self.mouse-x;
                drag-start-y = self.mouse-y;
            } else if (ev.kind == PointerEventKind.up) {
                drag-pressed = false;
            }
        }
    }
}
